version: '3'

services:
  dual-ai-chat:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
    # 添加健康检查
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    # 限制资源使用
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
